language: php
php:
# not working anymore  - '7.0.32'
  - '7.1.26'
  - '7.2.15'
  - '7.3.2'
# https://github.com/sebastianbergmann/phpunit/issues/2581
#  - hhvm
# 201902213
# PHP8.0.0-dev does not work with current dependencies
#  - nightly

before_script:
  - travis_retry curl -s http://getcomposer.org/installer | php
  - travis_retry php composer.phar install -n

# Explicitly use the phpunit from composer, not any system-wide found
script: 
#  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml --testdox tests
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.xml tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - php vendor/bin/codacycoverage clover coverage.xml

addons:
  apt:
    packages:
    - sendmail 
