name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: php-actions/composer@v6
      with:
        php_version: "8.4.10"
    - name: PHPUnit tests
      uses: php-actions/phpunit@v4
      env:
        XDEBUG_MODE: coverage
      with:
        test_suffix: "Test.php" # get rid of warning after updating to PHPUnit11
        php_extensions: "xdebug mbstring xml curl"
        configuration: "./phpunit.xml"
        coverage_clover: "coverage.xml"
        version: "12.3.15" # keep in sync with composer version
        php_version: "8.4.10"

    - name: Code coverage with codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
