name: CI

on: [push]

# git show 7fe70e20d965116236fa0bae8132d46d043647f5
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: PHPUnit tests
      uses: php-actions/phpunit@v4
      env:
        XDEBUG_MODE: coverage
      with:
        test_suffix: "Test.php" # get rid of warning after updating to PHPUnit11
        php_extensions: "xdebug mbstring xml curl"
        configuration: "./phpunit.xml"
        coverage_clover: "coverage.xml"
        version: "12.2.7"
        php_version: "8.4.10"

    - name: Code coverage with codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
