name: CI

on: [push]

# git show 7fe70e20d965116236fa0bae8132d46d043647f5
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_extensions: "xdebug mbstring xml"
        configuration: "phpunit.xml"
        coverage_clover: "coverage.xml"
        version: "9.6.7"
        php_version: "8.2"

# TODO: integrate Coverage https://about.codecov.io/blog/measuring-php-code-coverage-with-phpunit-and-github-actions/        
